/**
 * \brief Task priorities
 */

#ifndef PRIORITIES_H
#define PRIORITIES_H

#define PRIORITY_TCP_SERVER 210
#define PRIORITY_UDP_SERVER 210
#define PRIORITY_UDP_CLIENT 200
#define PRIORITY_MOTOR_WRITER 50
#define PRIORITY_MOTOR_READER 50

#endif
